query getNotifications {
  getNotifications {
    id
    status
    type
    sender {
      id
      firstName
      lastName
    }
    group {
      id
      challengeName
      startDate
      endDate
    }
  }
}
