query GetUserEcoAction($groupId: Int!, $ecoActionId: Int!) {
  getUserEcoAction(groupId: $groupId, ecoActionId: $ecoActionId) {
    id
    proof
    hasLiked
    validationId
    groupId
    ecoAction {
      name
      description
      likes
    }
  }
}
