mutation RemoveUserFromGroup($data: GroupInputAddOneUser!) {
  removeUserFromGroup(data: $data) {
    teams {
      id
      users {
        id
        firstName
        lastName
      }
    }
    users {
      id
      firstName
      lastName
    }
  }
}
