FROM node:lts-alpine

RUN apk --no-cache add curl
RUN apk add make g++ python3 git
RUN npm i -g node-pre-gyp
RUN npm i -g pnpm

RUN mkdir /app
WORKDIR /app

COPY package*.json ./
COPY pnpm* .
COPY .npmrc .
RUN pnpm i

COPY tsconfig.json ./
COPY free-eco-actions.json ./
COPY src ./

# tanspile TS into JS for perf
RUN ["pnpm", "run", "build"]

# the command that starts our app
CMD ["pnpm", "run", "start:prod"]