name: integration-tests-workflow

on: pull_request

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Go to integration-tests and run tests
        run: cd integration-tests && npm i && npm test
